name: Release Train

on:
    push:
        branches: ["main"]

permissions:
    contents: write
    pull-requests: write

env:
    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                node-version-file: .nvmrc
                cache: "npm"
            - uses: ./.github/actions/install
            - uses: ./.github/actions/lint

    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                node-version-file: .nvmrc
                cache: "npm"
            - uses: ./.github/actions/install
            - uses: ./.github/actions/build

    release-please:
        runs-on: ubuntu-latest

        needs: [test, lint]

        steps:
          - uses: actions/checkout@v4
          - uses: googleapis/release-please-action@v4
            id: release
            with:
              release-type: node
          - uses: actions/setup-node@v1
            with:
              node-version-file: .nvmrc
              cache: "npm"
            if: ${{ steps.release.outputs.release_created }}
          - uses: ./.github/actions/install
            if: ${{ steps.release.outputs.release_created }}
          - uses: ./.github/actions/build
            if: ${{ steps.release.outputs.release_created }}
          - uses: ./.github/actions/publish
            if: ${{ steps.release.outputs.release_created }}
